themeVariant:
  - auto
  - contao-light
  - contao-dark
disableSearch: false
disableLanguageSwitch: true
documentation_label: Documentation
showVisitedLinks: true
disableInlineCopyToClipBoard: true
#disableAssetsBusting: true
currentContaoVersion: '4.13'
disableLandingPageButton: true
showBanner: true
bannerTitleDE: Contao Konferenz & College Düsseldorf 2025
bannerTitleEN: Contao Conference & College Düsseldorf 2025
bannerDateDE: 25. bis 27. September
bannerDateEN: 25th to 27th September
bannerUrlDE: https://to.contao.org/conference
bannerUrlEN: https://to.contao.org/conference
