themeVariant:
  - auto:
      - contao-light
      - contao-dark
    identifier: auto-theme
    name: Auto
  - identifier: contao-light
    name: Light
  - identifier: contao-dark
    name: Dark
search:
  disable: false
disableLanguageSwitch: true
documentation_label: Documentation
disableInlineCopyToClipBoard: true
currentContaoVersion: '5.5'
currentReleaseCandidate: '5.6'
disableLandingPageButton: true
banner:
  show: true
  url: https://to.contao.org/conference
hideAuthorName: true
hideAuthorEmail: true
hideAuthorDate: true
disableExplicitIndexURLs: true
sidebarheadermenus: []
sidebarfootermenus:
  -
      type: custom
      identifier: footercontrols
      elements:
        - type: languageswitcher
        - type: versionswitcher
        - type: variantswitcher
