name: Build and deploy to https://docs.contao.org

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.150.0'
            - name: Build user manual
              run: make build-manual
            - name: Build developer manual
              run: make build-dev
            - name: Deploy user manual
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: 'build/manual'
                  target: ${{ secrets.DEPLOY_TARGET_PATH }}/5.x/manual
                  rm: true
                  strip_components: 2
            - name: Deploy developer manual
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: 'build/dev'
                  target: ${{ secrets.DEPLOY_TARGET_PATH }}/5.x/dev
                  rm: true
                  strip_components: 2
            - name: Deploy .htaccess
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: 'docs/.htaccess'
                  target: ${{ secrets.DEPLOY_TARGET_PATH }}
                  rm: false
                  strip_components: 1
                  overwrite: true
